In [ ]:
"cargar los datos"
from google.colab import files
uploaded = files.upload()

Saving big_bang_theory_dataset.csv to big_bang_theory_dataset.csv


In [ ]:
"importar librería de panda para hacer la tabla"
import pandas as pd
import io
Big_bang = pd.read_csv(io.BytesIO(uploaded["big_bang_theory_dataset.csv"]))
Big_bang.head(2)

Unnamed: 0       Location Scene  \
0           0  The apartment   NaN   
1           1  The apartment   NaN   

                                                Text  Speaker  Season  
0                              Again I’m right here.  Leonard       3  
1  Fine. The record shall so reflect. Now getting...  Sheldon       5

In [ ]:
"Comparativa de las veces que dice Sheldon la palabra Penny"
Big_bang.loc[(Big_bang.Speaker == "Sheldon")&(Big_bang["Text"].str.contains("Penny"))]

Unnamed: 0                     Location  \
35             35                  Penny’s car   
47             47                 Penny’s door   
125           125  Sheldon and Amy’s apartment   
185           185                The apartment   
503           503            Penny’s apartment   
...           ...                          ...   
38332       38332        The following morning   
38424       38424              Amy’s apartment   
38590       38590              The living room   
38708       38708            Penny’s apartment   
38876       38876             The laundry room   

                                                   Scene  \
35                                                   NaN   
47                                                   NaN   
125                                                  NaN   
185                                                  NaN   
503     Sheldon and Leonard are trying to construct f...   
...                                                  ...   
38332   Sheldon is in the kitchen making breakfast, H...   
38424                             Amy is playing a harp,   
38590   Leonard enters in his dressing gown, There is...   
38708                                                NaN   
38876                                                NaN   

                                                    Text  Speaker  Season  
35       Because he’s not like us Penny. We’re dreamers.  Sheldon       7  
47                                                Penny.  Sheldon       4  
125    This isn’t fair. You’ve discussed aspects of o...  Sheldon      10  
185    Penny please we’re facing a far more serious p...  Sheldon       2  
503         Hang on Penny. How about fans here and here?  Sheldon       1  
...                                                  ...      ...     ...  
38332  Well then it’s all settled Christie will stay ...  Sheldon       1  
38424  Penny has dragged a chair in off the street wh...  Sheldon       5  
38590  But we did convince him to leave the motel. Co...  Sheldon       1  
38708                                             Penny!  Sheldon       5  
38876  Yes Penny has a lot of her money tied up in pr...  Sheldon       5  

[367 rows x 6 columns]

In [ ]:
"Comparativa de las veces que dice Sheldon concretamente Penny."
Big_bang.loc[(Big_bang.Speaker == "Sheldon")&(Big_bang.Text == "Penny.")]

Unnamed: 0                Location  \
1722         1722              The stairs   
2477         2477       Penny’s apartment   
13029       13029         At Penny’s door   
16842       16842    Outside Penny’s door   
26974       26974       Penny’s apartment   
36322       36322  Penny’s apartment door   

                                                   Scene    Text  Speaker  \
1722    Sheldon is playing on his computer at the end...  Penny.  Sheldon   
2477                                                 NaN  Penny.  Sheldon   
13029                        Leonard knocks three times,  Penny.  Sheldon   
16842                                                NaN  Penny.  Sheldon   
26974                                                NaN  Penny.  Sheldon   
36322                        Sheldon knocks three times,  Penny.  Sheldon   

       Season  
1722        2  
2477        2  
13029       4  
16842       2  
26974       2  
36322       5

In [ ]:
"histograma de las veces que Sheldon dice Penny"
import numpy as np
import pandas as pd
from scipy import stats, integrate
import matplotlib.pyplot as plt
import seaborn as sns

fig, axs = plt.subplots(2, 1, figsize=(15,6))

sns.histplot(data = Big_bang.loc[(Big_bang.Speaker == "Sheldon") & (Big_bang.Text.str.contains("Penny",case=False))],x = "Location", ax = axs[0],color = "green")

sns.histplot(data = Big_bang.loc[(Big_bang.Speaker == "Sheldon") & (Big_bang.Text == "Penny.")], x = "Location", ax=axs[1], color = "orange")

lines = []
labels =[]
axLine = 0
axLabel = 0

for ax in fig.axes:

  axLine, axLabel = ax.get_legend_handles_labels()
  lines.extend(axLine)
  labels.extend(axLabel)

fig.legend(lines, labels, loc = "upper right")

plt.show()

In [ ]:
"Gráfica de las veces que Sheldon dice Penny"
import seaborn as sns
sns.set_theme(style="whitegrid")

Muestra = Big_bang

cmap = sns.cubehelix_palette(rot=-.2, as_cmap=True)

Graph_1 = sns.relplot(data = Muestra,x="Location", y="Speaker", sizes=(10, 200))



In [ ]:
"Buscar las veces que dice Penny y crear columnas para contarlo"

import pandas as pd
import numpy as np
Big_bang["Say_Penny"] = Big_bang["Text"].str.match("Penny")
Big_bang["Contar_Say_Penny"] = np.where(Big_bang["Say_Penny"]==True,"1","0")
Big_bang.head(5)

Unnamed: 0                   Location  \
0           0              The apartment   
1           1              The apartment   
2           2   The room in the basement   
3           3  Sheldon and Amy’s bedroom   
4           4                   A cinema   

                                               Scene  \
0                                                NaN   
1                                                NaN   
2   Sheldon enters, takes out a box, takes a bean...   
3                                                NaN   
4                                                NaN   

                                                Text  Speaker  Season  \
0                              Again I’m right here.  Leonard       3   
1  Fine. The record shall so reflect. Now getting...  Sheldon       5   
2  One two three four five six seven eight… Drat....  Sheldon       6   
3  I’m not sure. Earlier tonight things began org...  Sheldon      10   
4              He’s finding the acoustic sweet spot.  Leonard       2   

  Say_Penny Contar_Say_Penny  
0     False                0  
1     False                0  
2     False                0  
3     False                0  
4     False                0

In [ ]:
"Cuantas veces se dice la palabra Penny"
Big_bang.Say_Penny.value_counts()

False    37547
True       141
Name: Say_Penny, dtype: int64

In [ ]:
"Crear dataFrame nuevo para contar por season e indice las veces que se dice Penny "
Big_bang_2 = Big_bang.groupby(["Season","Speaker"]).Contar_Say_Penny.agg(["sum"]).reset_index()
Big_bang_2["Indice"] = Big_bang_2.groupby(["Speaker"]).ngroup()
Big_bang_2["Veces_Penny"] = Big_bang_2["sum"]
Big_bang_2 = Big_bang_2[["Season","Speaker","Veces_Penny","Indice"]] 
Big_bang_2.head(5)

Season  Speaker                                        Veces_Penny  Indice
0       1   Howard  0000100000000000000000000000000000000000000000...       0
1       1  Leonard  0000000000000000000000000000000000000000010000...       1
2       1    Penny  0000000000000000000000000000000000000000000000...       2
3       1      Raj  0000000000000000000000000000000000000000000000...       3
4       1  Sheldon  0000000000000000000000000000000000000000000000...       4

In [ ]:
"En esta parte me ayudó un compañero, pero la verdad es que no me queda muy claro porqué esta haciendo todo esto"
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(Big_bang_2.Indice, Big_bang_2.Veces_Penny, test_size = 0.20, random_state=0)

In [ ]:
logisticRegr = LogisticRegression()

In [ ]:
logisticRegr.fit(x_train.values.reshape(-1,1), y_train)

LogisticRegression()

In [ ]:
predictions = logisticRegr.predict(x_test.values.reshape(-1,1))

In [ ]:
score = logisticRegr.score(x_test.values.reshape(-1,1), y_test)
print (score)

0.0


In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics

cm = metrics.confusion_matrix(y_test, predictions)
print (cm)

[[0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0]]
